#!/usr/bin/perl
#
# Author : Alexi Langlade
# Inspired by Rodolphe Quiedeville(2006) & Andreas Buer(2004)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# Parameters:
#
#   config
#   autoconf
#
# Configuration variables
#
#   mysqlopts     - Options to pass to mysql
#   mysqladmin    - Override location of mysqladmin
#
#%# family=auto
#%# capabilities=autoconf

use strict;

my $MYSQLADMIN = $ENV{mysqladmin} || "mysqladmin";
my $COMMAND    = "$MYSQLADMIN $ENV{mysqlopts} extended-status";

my %WANTED = ( "Created_tmp_disk_tables" => "Created tmp Disk Tables",
				"Created_tmp_files" => "Created tmp Files",
				"Created_tmp_tables" => "Created tmp Tables");

my %WANTEDDRAW = ("Created_tmp_disk_tables" => "AREA",
                "Created_tmp_files" => "LINE1",
                "Created_tmp_tables" => "LINE1");

my $arg = shift();

if ($arg eq 'config') {
    print_config();
    exit();
} elsif ($arg eq 'autoconf') {
    unless (test_service() ) {
        print "yes\n";
    } else {
        print "no\n";
    }
    exit;
}


open(SERVICE, "$COMMAND |")
  or die("Could not execute '$COMMAND': $!");

while (<SERVICE>) {
    my ($k, $v) = (m/(\w+).*?(\d+(?:\.\d+)?)/);
    next unless ($k);
    if (exists $WANTED{$k} ) {
	print("$k.value $v\n");
    }
}

close(SERVICE);

sub print_config {

    print('graph_title MySQL Temporary Objects
graph_args --base 1000
graph_vlabel objects
graph_category mysql
graph_info The MySQL Temporary Objects graph shows information about temporary objects created by the MySQL server: temporary tables, temporary files, and temporary tables created on disk instead of in memory. Like sort data, this is easy to over-analyze. The most serious one is the temp tables created on disk.
');

    for my $key (keys %WANTED) {
        print("$key.label $WANTED{$key}\n",
              "$key.min 0\n",
              "$key.type DERIVE\n",
              "$key.max 100000000\n",
              "$key.draw ".$WANTEDDRAW{$key}."\n",
             );
    }
    
}


sub test_service {

    my $return = 1;

    system ("$MYSQLADMIN --version >/dev/null 2>/dev/null");
    if ($? == 0)
    {
    	system ("$COMMAND >/dev/null 2>/dev/null");
    	if ($? == 0)
    	{
    	    print "yes\n";
    	    $return = 0;
    	}
    	else
    	{
    	    print "no (could not connect to mysql)\n";
    	}
    }
    else
    {
	print "no (mysqladmin not found)\n";
    }
    exit $return;
}
