#!/bin/bash

statusfile="/tmp/apccache-hits.txt"

SCRIPT_NAME=/munin-apccache.php SCRIPT_FILENAME=/usr/share/munin/plugins/munin-apccache.php QUERY_STRING="what=hits" REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 > $statusfile 2> /dev/null

if [ "$1" = "config" ]; then
    pool=$(awk '/pool/{print $2}' $statusfile)
    echo "graph_title APC Cache Hits"
    echo "graph_vlabel hits"
    echo "graph_category apccache"
    echo "apccache_hits.label APC Cache Hits"
    echo "apccache_hits.type DERIVE"
    echo "apccache_hits.min 0"
    echo "apccache_hits.draw LINE2"
    echo "apccache_misses.label APC Cache Misses"
    echo "apccache_misses.type DERIVE"
    echo "apccache_misses.min 0"
    echo "apccache_misses.draw LINE2"
        exit 0
else
    awk '
    /^apccache_hits.value/ {print "apccache_hits.value " $2}
    /^apccache_misses.value/{print "apccache_misses.value " $2}
    ' < $statusfile
fi

rm -f $statusfile